# Does the data contain larry data or not
# --------------------------------------------------------------------------------
feature_bc: True


# Feature and cellular barcode fastq files
# --------------------------------------------------------------------------------
read_feature_bc : "R2" # Fastq containing LARRY bc. Can be R1 or R2. Default: R2
read_cellular_bc: "R1" # Fastq containing the cellular barcode. Default: R1


# Hamming distance to collapse barcodes with umicollapse
# --------------------------------------------------------------------------------
hamming_distance: 3  # Hamming distance to collapse barcodes with umicollapse
#reads_cutoff    : 10 # Minimum amount of reads to call a LARRY UMI
#umi_cutoff      : 3  # Minimum number of UMIs to consider a LARRY barcode as detected


# LARRY BARCODE PATTERNS
# --------------------------------------------------------------------------------
# Structure --> barcode-sequence : barcode name
# i.e: "ACGT..GTA..GCC..GGGTA..GA" : "Scarlet"
# Special characters won't be escaped.  
bc_patterns:
  "GATCC..GT....TG....CA....." : "LARRYv1"